services:
  yii2:
    container_name: yii2_api_container
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=yii2db
      - DB_USERNAME=yii2user
      - DB_PASSWORD=123456
      - JWT_SECRET=secret
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "composer install --prefer-dist && apache2-foreground"]

  mysql:
    container_name: mysql_container
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'adminpass'
      MYSQL_DATABASE: 'yii2db'
      MYSQL_USER: 'yii2user'
      MYSQL_PASSWORD: '123456'
    ports:
      - '3306:3306'

volumes:
  mysql_data: